version: '3.8'

services:
  filament_app:
    build: .
    container_name: filament_app
    ports:
      - "5050:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    env_file: .env
    environment:
      # These can also override .env values if needed
      SECRET_KEY: ${SECRET_KEY}
      FERNET_KEY: ${FERNET_KEY}
      # BEHIND_PROXY: ${BEHIND_PROXY}
